/**
 * Verified production content, generated by `npm run content:import` from
 * content/politis-content.xlsx. Do not edit content.json by hand.
 */
import type { Benefit, Procedure } from '@/types/models';
import raw from './content.json';

interface PublishedContent {
  generatedAt: string | null;
  benefits: Benefit[];
  procedures: Procedure[];
}

export const publishedContent = raw as unknown as PublishedContent;

/** True when the editors have imported at least one benefit or procedure. */
export const hasPublishedContent = publishedContent.benefits.length > 0 || publishedContent.procedures.length > 0;
