import { normalizeHeader } from "./parse";

/** Greek names for the columns of Booking.com and Airbnb exports (others are shown as they are). */
const LABELS: Record<string, string> = {
  "book number": "Αριθμός κράτησης",
  "booked by": "Κράτηση από",
  "guest name s": "Όνομα επισκέπτη",
  "guest name": "Όνομα επισκέπτη",
  "check in": "Άφιξη",
  "check out": "Αναχώρηση",
  "booked on": "Ημερομηνία κράτησης",
  booked: "Ημερομηνία κράτησης",
  status: "Κατάσταση",
  rooms: "Δωμάτια",
  people: "Άτομα",
  adults: "Ενήλικες",
  children: "Παιδιά",
  "children s ages": "Ηλικίες παιδιών",
  price: "Τιμή",
  "commission %": "Προμήθεια %",
  "commission amount": "Ποσό προμήθειας",
  "payment status": "Κατάσταση πληρωμής",
  "payment method": "Τρόπος πληρωμής",
  remarks: "Σχόλια / αιτήματα",
  "booker group": "Ομάδα επισκεπτών",
  "booker country": "Χώρα",
  "travel purpose": "Σκοπός ταξιδιού",
  device: "Συσκευή κράτησης",
  "unit type": "Τύπος μονάδας",
  "duration nights": "Νύχτες",
  "cancellation date": "Ημερομηνία ακύρωσης",
  address: "Διεύθυνση",
  "phone number": "Τηλέφωνο",
  "confirmation code": "Κωδικός επιβεβαίωσης",
  contact: "Επικοινωνία",
  "# of adults": "Ενήλικες",
  "# of children": "Παιδιά",
  "# of infants": "Βρέφη",
  "start date": "Άφιξη",
  "end date": "Αναχώρηση",
  "# of nights": "Νύχτες",
  listing: "Καταχώριση",
  earnings: "Αποδοχές",
};

export const platformFieldLabel = (header: string) => LABELS[normalizeHeader(header)] ?? header;
