-- Generated by `npm run content:import` on 2026-10-08T07:22:14.458Z. Do not edit by hand.
begin;
delete from public.benefit_rules;
delete from public.benefits;
delete from public.procedure_steps;
delete from public.procedures;
delete from public.sources where is_mock = false;
commit;
